before_script:
  - npm run getReady
build:
  stage: build
  script:
    - gulp gitlab
    - rsync -avzr --stats --delete-after --exclude 'node_modules' --exclude '/src' --exclude '.*' --exclude '.*/' ./dist/ deployer@demos.pixel2html.com:/home/deployer/www/demos/0000055/004118
    - curl -X POST -d "path=0000055/004118" http://deployer.pixel2html.com/html/demo_links_update

  only:
    - master
